# Generated by Django 4.1.9 on 2023-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="is_popularity",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
    ]
