# Generated by Django 4.1.9 on 2023-06-03 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_inventory_is_popularity_alter_inventory_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="is_popularity",
        ),
    ]
