# Generated by Django 4.1.9 on 2023-06-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_remove_inventory_is_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="num_views",
            field=models.IntegerField(default=0),
        ),
    ]
