# Generated by Django 4.1.9 on 2023-06-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_num_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="inventory",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="product.inventory"),
        ),
    ]
