# Generated by Django 4.1.9 on 2023-06-03 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_image_inventory_alter_stockcontrol_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="product.product"
            ),
        ),
    ]
