# Generated by Django 4.1.9 on 2023-06-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_inventory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockcontrol",
            name="last_checked",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
