# Generated by Django 4.1.9 on 2023-06-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_stockcontrol_last_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="is_feature",
            field=models.BooleanField(default=False),
        ),
    ]
