# Generated by Django 4.1.9 on 2023-06-23 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_image_is_feature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="img",
            new_name="url",
        ),
    ]
