# Generated by Django 4.1.9 on 2023-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_rename_img_category_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(upload_to="img/products"),
        ),
    ]
