# Generated by Django 4.1.9 on 2023-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_feature",
            field=models.BooleanField(default=False),
        ),
    ]
