# Generated by Django 4.1.9 on 2023-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_instagramimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(),
        ),
    ]
