# Generated by Django 4.1.9 on 2023-06-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About_US",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("img", models.ImageField(upload_to="img/about/")),
                ("title", models.CharField(max_length=150)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Meet_Our_Doctors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("img", models.ImageField(upload_to="img/about/Doctors")),
                ("name", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=50)),
                ("facebook", models.URLField()),
                ("twitter", models.URLField()),
                ("instagram", models.URLField()),
                ("linkedin", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Why_Choose_Us",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("text", models.TextField(max_length=250)),
            ],
        ),
    ]
