# Generated by Django 4.1.9 on 2023-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_about_us_meet_our_doctors_why_choose_us"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_us",
            name="message",
            field=models.CharField(default="asad", max_length=300),
            preserve_default=False,
        ),
    ]
