# Generated by Django 4.1.9 on 2023-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_about_us_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("icon", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("img", models.ImageField(upload_to="img/history/")),
                ("title", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("img", models.ImageField(upload_to="img/Information/")),
                ("text", models.TextField(max_length=250)),
            ],
        ),
    ]
