# Generated by Django 4.1.9 on 2023-06-06 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_customer_service_history_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="information",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customer_service",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="information",
            name="text",
            field=models.TextField(),
        ),
    ]
