# Generated by Django 4.1.9 on 2023-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_information_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
